### ISSUE TITLE
friendship heart ui does not move correctly with zoom and ui scale settings

### ISSUE THREAD

**Issue by AnukWarrior** [nakano15/terraguardians#43] opened 2024-03-22 23:24 UTC
changeing zoom or ui scale can mess with the hearts position and moving around can make it worse and setting ui scale to very high or very low can sometimes cause it to go off screen
![Screenshot 2024-03-23 122137](https://github.com/nakano15/terraguardians/assets/89364836/e63d9b23-a6ab-45a4-9b2d-bc3b5ddf3bca)
![Screenshot 2024-03-23 122147](https://github.com/nakano15/terraguardians/assets/89364836/33ca4adc-23f8-464b-ba81-7837a97b220d)

**Comment by nakano15** [comment] 2024-04-05 19:40
![image](https://github.com/nakano15/terraguardians/assets/1460392/e5736055-5edf-4994-959b-0831a2a78535)
I think the issue is now fixed. Next update will bring the fix.

**Closed as completed by nakano15** 2024-04-05 19:40 UTC
